<?xml version="1.0" encoding="utf-8"?><Database Name="QLFurnitures" Class="dbQLFurnituresDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-1FIP7S4;Initial Catalog=QLFurnitures;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="QLFurnituresConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CHITIETDONTHANG" Member="CHITIETDONTHANGs">
    <Type Name="CHITIETDONTHANG">
      <Column Name="MaDonHang" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNT" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="NOITHAT_CHITIETDONTHANG" Member="NOITHAT" ThisKey="MaNT" OtherKey="MaNT" Type="NOITHAT" IsForeignKey="true" />
      <Association Name="DONDATHANG_CHITIETDONTHANG" Member="DONDATHANG" ThisKey="MaDonHang" OtherKey="MaDonHang" Type="DONDATHANG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NOITHAT" Member="NOITHATs">
    <Type Name="NOITHAT">
      <Column Name="MaNT" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenNT" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="GiaBan" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BestSeller" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AnhBia" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgayCapNhat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SoLuongTon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaLoaiNT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaLoaiPhong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNSX" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="NOITHAT_CHITIETDONTHANG" Member="CHITIETDONTHANGs" ThisKey="MaNT" OtherKey="MaNT" Type="CHITIETDONTHANG" />
      <Association Name="LOAINOITHAT_NOITHAT" Member="LOAINOITHAT" ThisKey="MaLoaiNT" OtherKey="MaLoaiNT" Type="LOAINOITHAT" IsForeignKey="true" />
      <Association Name="LOAIPHONG_NOITHAT" Member="LOAIPHONG" ThisKey="MaLoaiPhong" OtherKey="MaLoaiPhong" Type="LOAIPHONG" IsForeignKey="true" />
      <Association Name="NHASANXUAT_NOITHAT" Member="NHASANXUAT" ThisKey="MaNSX" OtherKey="MaNSX" Type="NHASANXUAT" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DONDATHANG" Member="DONDATHANGs">
    <Type Name="DONDATHANG">
      <Column Name="MaDonHang" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DaThanhToan" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TinhTrangGiaoHang" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NgayDat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayGiao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MaND" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DONDATHANG_CHITIETDONTHANG" Member="CHITIETDONTHANGs" ThisKey="MaDonHang" OtherKey="MaDonHang" Type="CHITIETDONTHANG" />
      <Association Name="NGUOIDUNG_DONDATHANG" Member="NGUOIDUNG" ThisKey="MaND" OtherKey="MaND" Type="NGUOIDUNG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LOAINOITHAT" Member="LOAINOITHATs">
    <Type Name="LOAINOITHAT">
      <Column Name="MaLoaiNT" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLoaiNT" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="LOAINOITHAT_NOITHAT" Member="NOITHATs" ThisKey="MaLoaiNT" OtherKey="MaLoaiNT" Type="NOITHAT" />
    </Type>
  </Table>
  <Table Name="dbo.LOAIPHONG" Member="LOAIPHONGs">
    <Type Name="LOAIPHONG">
      <Column Name="MaLoaiPhong" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLoaiPhong" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="LOAIPHONG_NOITHAT" Member="NOITHATs" ThisKey="MaLoaiPhong" OtherKey="MaLoaiPhong" Type="NOITHAT" />
    </Type>
  </Table>
  <Table Name="dbo.NGUOIDUNG" Member="NGUOIDUNGs">
    <Type Name="NGUOIDUNG">
      <Column Name="MaND" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenND" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TaiKhoan" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="NGUOIDUNG_DONDATHANG" Member="DONDATHANGs" ThisKey="MaND" OtherKey="MaND" Type="DONDATHANG" />
    </Type>
  </Table>
  <Table Name="dbo.NGUOIQUANTRI" Member="NGUOIQUANTRIs">
    <Type Name="NGUOIQUANTRI">
      <Column Name="MaNQT" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TaiKhoanNQT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MatKhauNQT" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TenNQT" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.NHASANXUAT" Member="NHASANXUATs">
    <Type Name="NHASANXUAT">
      <Column Name="MaNSX" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenNSX" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Diachi" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="NHASANXUAT_NOITHAT" Member="NOITHATs" ThisKey="MaNSX" OtherKey="MaNSX" Type="NOITHAT" />
    </Type>
  </Table>
</Database>